# Generated by Django 3.1.2 on 2021-03-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='title',
        ),
    ]
